### ISSUE TITLE
ONNXRuntimeError - Trouble with setting up BetaSuite

### ISSUE THREAD

**Issue by Wombatant1** [solarorb93/BetaSuite#61]
Hi, 
I just found out about this censoring solution and I'm dying to try it out. However I just couldn't make it work. Every step including running betatest.py went without any problem. but when I try to run test censoring of local files I get response as below:

> B-Suite\BetaSuite-0.2.4>python betastare.py
2 0 2 3 - 0 4 - 0 6   2 3 : 2 0 : 1 8 . 2 5 9 6 5 4 9   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 3 6   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   S o m e   n o d e s   w e r e   n o t   a s s i g n e d   t o   t h e   p r e f e r r e d   e x e c u t i o n   p r o v i d e r s   w h i c h   m a y   o r   m a y   n o t   h a v e   a n   n e g a t i v e   i m p a c t   o n   p e r f o r m a n c e .   e . g .   O R T   e x p l i c i t l y   a s s i g n s   s h a p e   r e l a t e d   o p s   t o   C P U   t o   i m p r o v e   p e r f .
 2 0 2 3 - 0 4 - 0 6   2 3 : 2 0 : 1 8 . 2 6 4 5 4 4 9   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 3 8   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   R e r u n n i n g   w i t h   v e r b o s e   o u t p u t   o n   a   n o n - m i n i m a l   b u i l d   w i l l   s h o w   n o d e   a s s i g n m e n t s .
 Processing ../uncensored_pics/
--- Skipping  1/3 (failed)  [----- ----- ----- -----: -----]: 1p45872hy4sa1.webp
Error err=FileNotFoundError(2, 'No such file or directory'), type(err)=<class 'FileNotFoundError'>
--- Skipping  2/3 (failed)  [----- ----- ----- -----: -----]: test1.jpg
Error err=FileNotFoundError(2, 'No such file or directory'), type(err)=<class 'FileNotFoundError'>
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
--- Skipping  3/3 (failed)  [----- ----- ----- -----: -----]: test1.png
Error err=FileNotFoundError(2, 'No such file or directory'), type(err)=<class 'FileNotFoundError'>

I'm using GPU acceleration, but I get almost identical error when running it with CPU mode. 
I tried a solution from #60 , but it didn't do much

What is quite beyond me is that i tried to run betavision 3 times, and got different results each time
First, crashed at betavision-detect.py. I don't have a copy of cmd result but it listed a problem with 3 files:

> betavision-detect.py
line 82 ` ( local_out_0, local_out_1, local_out_2 ) = bu_model.get_raw_model_output( local_screenshots, session )`

> betautils-model.py
line 47 `(output[0][i], output[1][i], output[2][i]) = session.run( betaconst.model_outputs, {betaconst.model_input: [img_array[i]]})`

> C:\Users\MyUserName\AppData\Local\Programs\Python\Python39\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py
line 200 `return self._sess.run(output_names, input_feed, run_options)`

Second run was after trying CUDA reinstalation, with betaconfig.py framerate set at 5fps
It worked quite well, so I tried changing a size of window and picking up framerate to 15fps and end up with censoring focusing on female faces, rarely catching other targets. 

Is there something I'm missing or should I provide something more for you to advise me something? Thanks in advance!

**Comment by TCStiggy** [comment]
I got the same note:
```
F:\BetaSuite\BetaSuite-0.2.4>python betatv.py
2 0 2 3 - 0 4 - 1 0   2 1 : 1 4 : 0 9 . 1 0 6 4 4 4 3   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 3 6   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   S o m e   n o d e s   w e r e   n o t   a s s i g n e d   t o   t h e   p r e f e r r e d   e x e c u t i o n   p r o v i d e r s   w h i c h   m a y   o r   m a y   n o t   h a v e   a n   n e g a t i v e   i m p a c t   o n   p e r f o r m a n c e .   e . g .   O R T   e x p l i c i t l y   a s s i g n s   s h a p e   r e l a t e d   o p s   t o   C P U   t o   i m p r o v e   p e r f .
 2 0 2 3 - 0 4 - 1 0   2 1 : 1 4 : 0 9 . 1 1 1 9 7 7 6   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 3 8   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   R e r u n n i n g   w i t h   v e r b o s e   o u t p u t   o n   a   n o n - m i n i m a l   b u i l d   w i l l   s h o w   n o d e   a s s i g n m e n t s .
```

All of betastare, betatv and real-time betavision work well.
But the GPU isn't working, only CPU is working. Only the betavision-detect is using around 5% of GPU performance.

**Comment by maralasar** [comment]
I think I found the solution to this problem. 
Basically when running `pip install onnxruntime-gpu` version 1.14 is installed. According to the offical documentation of onnxruntime this version does only support CUDA 11.6 and cuDNN 8.5.0.96 for Windows.
Since the install directions for BetaSuite tell you to install CUDA 11.4 and cuDNN 8.2.x you need to install onnxruntime version 1.12 or 1.11.

For me running the following two lines fixed the problem!
```sh
>>> pip uninstall onnxrintime-gpu -y
>>> pip install onnxrintime-gpu==1.12
```

But to be honest, for censoring videos and images the performance benefit was not very large at 720p. For higher resolutions there is some benefit, but don't expect your runtimes to reduce by 5x or so :D
For the live censoring it is crucuil to have it running. My decent PC (Ryzen 5 5600X and RTX 3070) is running at 90%!

Edit:
Removed a typo from the two commands (see [comment](https://github.com/solarorb93/BetaSuite/issues/61#issuecomment-1623441454) below)

**Comment by CarmenRider** [comment]
> I think I found the solution to this problem. Basically when running `pip install onnxruntime-gpu` version 1.14 is installed. According to the offical documentation of onnxruntime this version does only support CUDA 11.6 and cuDNN 8.5.0.96 for Windows. Since the install directions for BetaSuite tell you to install CUDA 11.4 and cuDNN 8.2.x you need to install onnxruntime version 1.12 or 1.11.
> 
> For me running the following two lines fixed the problem!
> 
> ```shell
> >>> pip uninstall onnxrintime-gpu -y
> >>> pip install onnxrintime-gpu==1.12
> ```
> 
> But to be honest, for censoring videos and images the performance benefit was not very large at 720p. For higher resolutions there is some benefit, but don't expect your runtimes to reduce by 5x or so :D For the live censoring it is crucuil to have it running. My decent PC (Ryzen 5 5600X and RTX 3070) is running at 90%!

I got this error:
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.12 (from versions: 1.15.0, 1.15.1)
ERROR: No matching distribution found for onnxruntime-gpu==1.12

**Comment by maralasar** [comment]
> > I think I found the solution to this problem. Basically when running `pip install onnxruntime-gpu` version 1.14 is installed. According to the offical documentation of onnxruntime this version does only support CUDA 11.6 and cuDNN 8.5.0.96 for Windows. Since the install directions for BetaSuite tell you to install CUDA 11.4 and cuDNN 8.2.x you need to install onnxruntime version 1.12 or 1.11.
> > For me running the following two lines fixed the problem!
> > ```shell
> > >>> pip uninstall onnxrintime-gpu -y
> > >>> pip install onnxrintime-gpu==1.12
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But to be honest, for censoring videos and images the performance benefit was not very large at 720p. For higher resolutions there is some benefit, but don't expect your runtimes to reduce by 5x or so :D For the live censoring it is crucuil to have it running. My decent PC (Ryzen 5 5600X and RTX 3070) is running at 90%!
> 
> I got this error: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.12 (from versions: 1.15.0, 1.15.1) ERROR: No matching distribution found for onnxruntime-gpu==1.12

I just saw a typo in my two commands! I typed an **i** instead of an **u**!
Of course it has to be:
```
>>> pip uninstall onnxruntime-gpu -y
>>> pip install onnxruntime-gpu==1.12
```

**Comment by brfgsgdfhghhfg** [comment]
> > > I think I found the solution to this problem. Basically when running `pip install onnxruntime-gpu` version 1.14 is installed. According to the offical documentation of onnxruntime this version does only support CUDA 11.6 and cuDNN 8.5.0.96 for Windows. Since the install directions for BetaSuite tell you to install CUDA 11.4 and cuDNN 8.2.x you need to install onnxruntime version 1.12 or 1.11.
> > > For me running the following two lines fixed the problem!
> > > ```shell
> > > >>> pip uninstall onnxrintime-gpu -y
> > > >>> pip install onnxrintime-gpu==1.12
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > But to be honest, for censoring videos and images the performance benefit was not very large at 720p. For higher resolutions there is some benefit, but don't expect your runtimes to reduce by 5x or so :D For the live censoring it is crucuil to have it running. My decent PC (Ryzen 5 5600X and RTX 3070) is running at 90%!
> > 
> > 
> > I got this error: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.12 (from versions: 1.15.0, 1.15.1) ERROR: No matching distribution found for onnxruntime-gpu==1.12
> 
> I just saw a typo in my two commands! I typed an **i** instead of an **u**! Of course it has to be:
> 
> ```
> >>> pip uninstall onnxruntime-gpu -y
> >>> pip install onnxruntime-gpu==1.12
> ```

Hello friend! I had the same issue, and thanks to you I have fixed it! ...Just so another error can appear. Could you please help me? I believe I've done everything correctly, I dont understand why I'm getting this error:

`2 0 2 3 - 0 7 - 1 0   0 2 : 4 1 : 5 7 . 5 4 3 6 7 3 4   [ E : o n n x r u n t i m e : D e f a u l t ,   p r o v i d e r _ b r i d g e _ o r t . c c : 1 3 5 1   o n n x r u n t i m e : : T r y G e t P r o v i d e r I n f o _ C U D A ]   D : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ s e s s i o n \ p r o v i d e r _ b r i d g e _ o r t . c c : 1 1 3 1   o n n x r u n t i m e : : P r o v i d e r L i b r a r y : : G e t   [ O N N X R u n t i m e E r r o r ]   :   1   :   F A I L   :   L o a d L i b r a r y   f a i l e d   w i t h   e r r o r   1 2 6   " "   w h e n   t r y i n g   t o   l o a d   " C : \ U s e r s \ V l a d a \ A p p D a t a \ L o c a l \ P r o g r a m s \ P y t h o n \ P y t h o n 3 9 \ l i b \ s i t e - p a c k a g e s \ o n n x r u n t i m e \ c a p i \ o n n x r u n t i m e _ p r o v i d e r s _ c u d a . d l l "

 2 0 2 3 - 0 7 - 1 0   0 2 : 4 1 : 5 7 . 5 5 6 1 2 7 6   [ W : o n n x r u n t i m e : D e f a u l t ,   o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 6 4 0   o n n x r u n t i m e : : p y t h o n : : C r e a t e E x e c u t i o n P r o v i d e r I n s t a n c e ]   F a i l e d   t o   c r e a t e   C U D A E x e c u t i o n P r o v i d e r .   P l e a s e   r e f e r e n c e   h t t p s : / / o n n x r u n t i m e . a i / d o c s / e x e c u t i o n - p r o v i d e r s / C U D A - E x e c u t i o n P r o v i d e r . h t m l # r e q u i r e m e n t s   t o   e n s u r e   a l l   d e p e n d e n c i e s   a r e   m e t .`

Please help me!

**Comment by a5116638** [comment]
> > > > I think I found the solution to this problem. Basically when running `pip install onnxruntime-gpu` version 1.14 is installed. According to the offical documentation of onnxruntime this version does only support CUDA 11.6 and cuDNN 8.5.0.96 for Windows. Since the install directions for BetaSuite tell you to install CUDA 11.4 and cuDNN 8.2.x you need to install onnxruntime version 1.12 or 1.11.
> > > > For me running the following two lines fixed the problem!
> > > > ```shell
> > > > >>> pip uninstall onnxrintime-gpu -y
> > > > >>> pip install onnxrintime-gpu==1.12
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > But to be honest, for censoring videos and images the performance benefit was not very large at 720p. For higher resolutions there is some benefit, but don't expect your runtimes to reduce by 5x or so :D For the live censoring it is crucuil to have it running. My decent PC (Ryzen 5 5600X and RTX 3070) is running at 90%!
> > > 
> > > 
> > > I got this error: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.12 (from versions: 1.15.0, 1.15.1) ERROR: No matching distribution found for onnxruntime-gpu==1.12
> > 
> > 
> > I just saw a typo in my two commands! I typed an **i** instead of an **u**! Of course it has to be:
> > ```
> > >>> pip uninstall onnxruntime-gpu -y
> > >>> pip install onnxruntime-gpu==1.12
> > ```
> 
> Hello friend! I had the same issue, and thanks to you I have fixed it! ...Just so another error can appear. Could you please help me? I believe I've done everything correctly, I dont understand why I'm getting this error:
> 
> `2 0 2 3 - 0 7 - 1 0 0 2 : 4 1 : 5 7 . 5 4 3 6 7 3 4 [ E : o n n x r u n t i m e : D e f a u l t , p r o v i d e r _ b r i d g e _ o r t . c c : 1 3 5 1 o n n x r u n t i m e : : T r y G e t P r o v i d e r I n f o _ C U D A ] D : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ s e s s i o n \ p r o v i d e r _ b r i d g e _ o r t . c c : 1 1 3 1 o n n x r u n t i m e : : P r o v i d e r L i b r a r y : : G e t [ O N N X R u n t i m e E r r o r ] : 1 : F A I L : L o a d L i b r a r y f a i l e d w i t h e r r o r 1 2 6 " " w h e n t r y i n g t o l o a d " C : \ U s e r s \ V l a d a \ A p p D a t a \ L o c a l \ P r o g r a m s \ P y t h o n \ P y t h o n 3 9 \ l i b \ s i t e - p a c k a g e s \ o n n x r u n t i m e \ c a p i \ o n n x r u n t i m e _ p r o v i d e r s _ c u d a . d l l "
> 
> 2 0 2 3 - 0 7 - 1 0 0 2 : 4 1 : 5 7 . 5 5 6 1 2 7 6 [ W : o n n x r u n t i m e : D e f a u l t , o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 6 4 0 o n n x r u n t i m e : : p y t h o n : : C r e a t e E x e c u t i o n P r o v i d e r I n s t a n c e ] F a i l e d t o c r e a t e C U D A E x e c u t i o n P r o v i d e r . P l e a s e r e f e r e n c e h t t p s : / / o n n x r u n t i m e . a i / d o c s / e x e c u t i o n - p r o v i d e r s / C U D A - E x e c u t i o n P r o v i d e r . h t m l # r e q u i r e m e n t s t o e n s u r e a l l d e p e n d e n c i e s a r e m e t .`
> 
> Please help me!

onnxrintim, cuda and cudnn versions are inconsistent, please see: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

**Comment by hetisnietgay** [comment]
Sorry for necro but it's notable enough to me; Sometimes it has issues but I just replace the model file. I keep an extra one in case I just copy over when I have to. Stupid fix, but it's better than nothing.

**Comment by Kar-Lor** [comment]
> > > > > I think I found the solution to this problem. Basically when running `pip install onnxruntime-gpu` version 1.14 is installed. According to the offical documentation of onnxruntime this version does only support CUDA 11.6 and cuDNN 8.5.0.96 for Windows. Since the install directions for BetaSuite tell you to install CUDA 11.4 and cuDNN 8.2.x you need to install onnxruntime version 1.12 or 1.11.
> > > > > For me running the following two lines fixed the problem!
> > > > > ```shell
> > > > > >>> pip uninstall onnxrintime-gpu -y
> > > > > >>> pip install onnxrintime-gpu==1.12
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > But to be honest, for censoring videos and images the performance benefit was not very large at 720p. For higher resolutions there is some benefit, but don't expect your runtimes to reduce by 5x or so :D For the live censoring it is crucuil to have it running. My decent PC (Ryzen 5 5600X and RTX 3070) is running at 90%!
> > > > 
> > > > 
> > > > I got this error: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.12 (from versions: 1.15.0, 1.15.1) ERROR: No matching distribution found for onnxruntime-gpu==1.12
> > > 
> > > 
> > > I just saw a typo in my two commands! I typed an **i** instead of an **u**! Of course it has to be:
> > > ```
> > > >>> pip uninstall onnxruntime-gpu -y
> > > >>> pip install onnxruntime-gpu==1.12
> > > ```
> > 
> > 
> > Hello friend! I had the same issue, and thanks to you I have fixed it! ...Just so another error can appear. Could you please help me? I believe I've done everything correctly, I dont understand why I'm getting this error:
> > `2 0 2 3 - 0 7 - 1 0 0 2 : 4 1 : 5 7 . 5 4 3 6 7 3 4 [ E : o n n x r u n t i m e : D e f a u l t , p r o v i d e r _ b r i d g e _ o r t . c c : 1 3 5 1 o n n x r u n t i m e : : T r y G e t P r o v i d e r I n f o _ C U D A ] D : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ s e s s i o n \ p r o v i d e r _ b r i d g e _ o r t . c c : 1 1 3 1 o n n x r u n t i m e : : P r o v i d e r L i b r a r y : : G e t [ O N N X R u n t i m e E r r o r ] : 1 : F A I L : L o a d L i b r a r y f a i l e d w i t h e r r o r 1 2 6 " " w h e n t r y i n g t o l o a d " C : \ U s e r s \ V l a d a \ A p p D a t a \ L o c a l \ P r o g r a m s \ P y t h o n \ P y t h o n 3 9 \ l i b \ s i t e - p a c k a g e s \ o n n x r u n t i m e \ c a p i \ o n n x r u n t i m e _ p r o v i d e r s _ c u d a . d l l "
> > 2 0 2 3 - 0 7 - 1 0 0 2 : 4 1 : 5 7 . 5 5 6 1 2 7 6 [ W : o n n x r u n t i m e : D e f a u l t , o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 6 4 0 o n n x r u n t i m e : : p y t h o n : : C r e a t e E x e c u t i o n P r o v i d e r I n s t a n c e ] F a i l e d t o c r e a t e C U D A E x e c u t i o n P r o v i d e r . P l e a s e r e f e r e n c e h t t p s : / / o n n x r u n t i m e . a i / d o c s / e x e c u t i o n - p r o v i d e r s / C U D A - E x e c u t i o n P r o v i d e r . h t m l # r e q u i r e m e n t s t o e n s u r e a l l d e p e n d e n c i e s a r e m e t .`
> > Please help me!
> 
> onnxrintim, cuda and cudnn versions are inconsistent, please see: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

I'm getting the same problem. I've verified my versions for everything.
onnxruntime-gpu is version 1.12
CUDA is version 11.4
**cuDNN says it's version 6.14.11.6050** (according to the Properties of Install Folder > cuda > bin > cudnn64_8.dll)

I specifically downloaded cuDNN 8.2.2 for CUDA 11.4, so I have no idea how this happened.
My only programming skills are a working knowledge of R, so I'm totally out of my depth with this.

**Comment by terran9001** [comment]
@Kar-Lor holy sh*t, this fixed it for me (simply using 1.12) . Thank-you for sharing this.

**Comment by Kar-Lor** [comment]
> @Kar-Lor holy sh*t, this fixed it for me (simply using 1.12) . Thank-you for sharing this.

Glad that helped!

Could you do me a solid and check what version of a couple things you're using? Once upon a time I had this working, but I updated some things when playing around with Stable Diffusion and now it's broken.

This is all assuming you're on Windows.
I'd appreciate it if you could copy-paste the output of these CMD inputs.

1. python --version
2. pip list
3. nvcc --version

Then go to the betasuite install folder > cuda > bin 
right-click on "cudnn64_8.dll"
select "properties" and go to the "Details" tab
copy/paste what it says on the lines for "Product name" and "Product version"

**Comment by terran9001** [comment]
@Kar-Lor I'm on Linux, however... 



Python 3.10.12

Package                      Version
---------------------------- ----------------
absl-py                      2.0.0
apt-clone                    0.2.1
apturl                       0.5.2
asttokens                    2.4.1
astunparse                   1.6.3
beautifulsoup4               4.10.0
blinker                      1.4
Brlapi                       0.8.3
Brotli                       1.0.9
cachetools                   5.3.2
catfish                      4.16.4
ccsm                         0.9.14.1
certifi                      2020.6.20
chardet                      4.0.0
click                        8.0.3
colorama                     0.4.4
coloredlogs                  15.0.1
command-not-found            0.3
compizconfig-python          0.9.14.1
configobj                    5.0.6
contourpy                    1.2.0
cryptography                 3.4.8
cupshelpers                  1.0
cycler                       0.12.1
Cython                       3.0.5
dbus-python                  1.2.18
decorator                    5.1.1
defer                        1.0.6
distlib                      0.3.7
distro                       1.7.0
enum34                       1.1.10
exceptiongroup               1.1.3
executing                    2.0.1
eyeD3                        0.8.10
ffmpeg-python                0.2.0
filelock                     3.13.1
flatbuffers                  23.5.26
fonttools                    4.44.3
fsspec                       2023.10.0
future                       0.18.3
gast                         0.5.4
google-auth                  2.23.4
google-auth-oauthlib         1.1.0
google-pasta                 0.2.0
grpcio                       1.59.3
h5py                         3.10.0
httplib2                     0.20.2
humanfriendly                10.0
idna                         3.3
ifaddr                       0.1.7
imageio                      2.32.0
IMDbPY                       2021.4.18
imgaug                       0.4.0
importlib-metadata           4.6.4
ipython                      8.17.2
jedi                         0.19.1
jeepney                      0.7.1
Jinja2                       3.1.2
keras                        2.15.0
keyring                      23.5.0
kiwisolver                   1.4.5
launchpadlib                 1.10.16
lazr.restfulclient           0.14.4
lazr.uri                     1.0.6
lazy_loader                  0.3
libclang                     16.0.6
louis                        3.20.0
Mako                         1.1.3
Markdown                     3.5.1
MarkupSafe                   2.1.3
matplotlib                   3.8.2
matplotlib-inline            0.1.6
menulibre                    2.2.2
ml-dtypes                    0.2.0
more-itertools               8.10.0
mpmath                       1.3.0
mss                          9.0.1
mugshot                      0.4.3
mutagen                      1.45.1
netaddr                      0.8.0
netifaces                    0.11.0
networkx                     3.2.1
nudenet                      3.0.8
numpy                        1.26.2
nvidia-cublas-cu12           12.1.3.1
nvidia-cuda-cupti-cu12       12.1.105
nvidia-cuda-nvrtc-cu12       12.1.105
nvidia-cuda-runtime-cu12     12.1.105
nvidia-cudnn-cu12            8.9.2.26
nvidia-cufft-cu12            11.0.2.54
nvidia-curand-cu12           10.3.2.106
nvidia-cusolver-cu12         11.4.5.107
nvidia-cusparse-cu12         12.1.0.106
nvidia-nccl-cu12             2.18.1
nvidia-nvjitlink-cu12        12.3.101
nvidia-nvtx-cu12             12.1.105
oauthlib                     3.2.0
onboard                      1.4.1
onnxruntime                  1.16.2
onnxruntime-gpu              1.12.0
opencv-contrib-python        4.8.1.78
opencv-python                4.8.1.78
opencv-python-headless       4.8.1.78
opt-einsum                   3.3.0
packaging                    21.3
pandas                       2.1.3
parso                        0.8.3
pexpect                      4.8.0
Pillow                       9.0.1
pip                          22.0.2
pipenv                       2023.11.15
platformdirs                 3.11.0
prompt-toolkit               3.0.41
protobuf                     4.23.4
psutil                       5.9.0
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycairo                      1.20.1
pycryptodomex                3.11.0
pycups                       2.0.1
pycurl                       7.44.1
pyelftools                   0.27
Pygments                     2.17.0
PyGObject                    3.42.1
PyICU                        2.8.1
PyJWT                        2.3.0
PyNaCl                       1.5.0
pyparsing                    2.4.7
pyparted                     3.11.7
PyQt5                        5.15.6
PyQt5-sip                    12.9.1
python-apt                   2.4.0+ubuntu3
python-dateutil              2.8.2
python-debian                0.1.43+ubuntu1.1
python-gnupg                 0.4.8
python-magic                 0.4.24
python-mpv                   1.0.5
pytz                         2023.3.post1
pyxattr                      0.7.2
pyxdg                        0.27
PyYAML                       5.4.1
reportlab                    3.6.8
requests                     2.25.1
requests-file                1.5.1
requests-oauthlib            1.3.1
rsa                          4.9
scikit-image                 0.22.0
scipy                        1.11.4
SecretStorage                3.3.1
setproctitle                 1.2.2
setuptools                   68.2.2
shapely                      2.0.2
six                          1.16.0
soupsieve                    2.3.1
stack-data                   0.6.3
style                        1.1.0
sympy                        1.12
systemd-python               234
tensorboard                  2.15.1
tensorboard-data-server      0.7.2
tensorflow                   2.15.0
tensorflow-estimator         2.15.0
tensorflow-io-gcs-filesystem 0.34.0
termcolor                    2.3.0
tifffile                     2023.9.26
tldextract                   3.1.2
torch                        2.1.1
torchvision                  0.16.1
traitlets                    5.13.0
triton                       2.1.0
typing_extensions            4.8.0
tzdata                       2023.3
ubuntu-drivers-common        0.0.0
ufw                          0.36.1
Unidecode                    1.3.3
update                       0.0.1
urllib3                      1.26.5
virtualenv                   20.24.6
wadllib                      1.3.6
wcwidth                      0.2.10
websockets                   9.1
Werkzeug                     3.0.1
wheel                        0.37.1
winregistry                  1.1.1
wrapt                        1.14.1
wslwinreg                    1.0.7
xdg                          5
xkit                         0.0.0
xlrd                         1.2.0
youtube-dl                   2021.12.17
yt-dlp                       2022.4.8
zipp                         1.0.0

I'm not using the cuda thing

**Comment by Subbie86** [comment]
Just got this error, and fixed it by installing 1.12.
However, after that I got a numpy error:
```
c:\Betasuite\BetaSuite-0.2.4>python betatest.py

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Betasuite\BetaSuite-0.2.4\betatest.py", line 15, in <module>
    import onnxruntime
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import (
  File "C:\Users\<username>\AppData\Roaming\Python\Python39\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an error set
```


I fixed that by running `pip install --upgrade numpy==1.26.4`
