### ISSUE TITLE
Error at running BetaVision with python betavision-detect.py

### ISSUE THREAD

**Issue by XiiiluX** [solarorb93/BetaSuite#74]
So, I had a few issues with GPU and decided to switch back to CPU, I uninstalled _onnxruntime_ and started to run BetaVision. I "started the process" with "_python betavision-screenshot.py_", and... everything was going fine. 
Now, I'm facing an issue with the second part which is about _python betavision-screenshot.py_. 
So, when i finally enter it into the cmd, i have this issue showing : 

D:\BetaSuite\BetaSuite-0.2.4>python betavision-censor.py
Traceback (most recent call last):
  File "D:\BetaSuite\BetaSuite-0.2.4\betavision-censor.py", line 16, in <module>
    outputs_0_shm = shared_memory.SharedMemory( name=betaconst.bv_detect_shm_0_name )
  File "C:\Users\ugoma\AppData\Local\Programs\Python\Python39\lib\multiprocessing\shared_memory.py", line 161, in __init__
    h_map = _winapi.OpenFileMapping(
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'bv_detect_shm_0_name'

Any troubleshooting would be appreciated ^^

**Comment by littleforabigguy** [comment]
Having the same/similar problem.

Running betavision-detect gives me

Traceback (most recent call last):
  File "C:\Users\name\Bsuite\BetaSuite-0.2.4\betavision-detect.py", line 14, in <module>
    in_timestamp1_shm = shared_memory.SharedMemory( name=betaconst.bv_ss_timestamp1_name )
  File "C:\Users\name\AppData\Local\Programs\Python\Python39\lib\multiprocessing\shared_memory.py", line 161, in __init__
    h_map = _winapi.OpenFileMapping(
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'bv_ss_timestamp1_name'

And betavision-censor gives

Traceback (most recent call last):
  File "C:\Users\name\Bsuite\BetaSuite-0.2.4\betavision-censor.py", line 16, in <module>
    outputs_0_shm = shared_memory.SharedMemory( name=betaconst.bv_detect_shm_0_name )
  File "C:\Users\name\AppData\Local\Programs\Python\Python39\lib\multiprocessing\shared_memory.py", line 161, in __init__
    h_map = _winapi.OpenFileMapping(
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'bv_detect_shm_0_name'
